//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CHITIETHD
{
    public string MAHD { get; set; }
    public string MALK { get; set; }
    public Nullable<int> SOLUONG { get; set; }
    public Nullable<decimal> DONGIA { get; set; }

    public virtual HOADON HOADON { get; set; }
    public virtual LINHKIEN LINHKIEN { get; set; }
}

public partial class HOADON
{
    public HOADON()
    {
        this.CHITIETHDs = new HashSet<CHITIETHD>();
    }

    public string MAHD { get; set; }
    public Nullable<System.DateTime> NGAYHD { get; set; }
    public string MAKH { get; set; }
    public Nullable<decimal> TONGTIEN { get; set; }

    public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
    public virtual KHACHHANG KHACHHANG { get; set; }
}

public partial class KHACHHANG
{
    public KHACHHANG()
    {
        this.HOADONs = new HashSet<HOADON>();
    }

    public string MAKH { get; set; }
    public string TENKH { get; set; }
    public Nullable<int> SĐT { get; set; }
    public string DIACHI { get; set; }

    public virtual ICollection<HOADON> HOADONs { get; set; }
}

public partial class LINHKIEN
{
    public LINHKIEN()
    {
        this.CHITIETHDs = new HashSet<CHITIETHD>();
    }

    public string MALK { get; set; }
    public string TENLK { get; set; }
    public string DUONGDAN { get; set; }
    public Nullable<System.DateTime> NGAYSX { get; set; }
    public Nullable<int> TGBH { get; set; }
    public string MALOAI { get; set; }
    public string THUONGHIEU { get; set; }
    public string MAUSAC { get; set; }
    public Nullable<decimal> GIA { get; set; }

    public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
    public virtual LOAILK LOAILK { get; set; }
}

public partial class LOAILK
{
    public LOAILK()
    {
        this.LINHKIENs = new HashSet<LINHKIEN>();
    }

    public string MALOAI { get; set; }
    public string TENLOAI { get; set; }

    public virtual ICollection<LINHKIEN> LINHKIENs { get; set; }
}
