//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class QLTHIETBIEntities : DbContext
{
    public QLTHIETBIEntities()
        : base("name=QLTHIETBIEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<CHITIETHD> CHITIETHDs { get; set; }
    public DbSet<HOADON> HOADONs { get; set; }
    public DbSet<KHACHHANG> KHACHHANGs { get; set; }
    public DbSet<LINHKIEN> LINHKIENs { get; set; }
    public DbSet<LOAILK> LOAILKs { get; set; }
}
